import api from './axios'

export const getThemeSettings = (storeId) => api.get(`/theme-settings/${storeId}`)
export const getPublicThemeSettings = (storeId) => api.get(`/theme-settings/public/${storeId}`)

export const updateColors = (storeId, data) => api.put(`/theme-settings/${storeId}/colors`, data)
export const updateTypography = (storeId, data) => api.put(`/theme-settings/${storeId}/typography`, data)
export const updateLayout = (storeId, data) => api.put(`/theme-settings/${storeId}/layout`, data)
export const updateHeader = (storeId, data) => api.put(`/theme-settings/${storeId}/header`, data)
export const updateFooter = (storeId, data) => api.put(`/theme-settings/${storeId}/footer`, data)
export const updateButtons = (storeId, data) => api.put(`/theme-settings/${storeId}/buttons`, data)
export const updateBadges = (storeId, data) => api.put(`/theme-settings/${storeId}/badges`, data)
export const updateIcons = (storeId, data) => api.put(`/theme-settings/${storeId}/icons`, data)
export const updateImages = (storeId, data) => api.put(`/theme-settings/${storeId}/images`, data)
export const updateProductPage = (storeId, data) => api.put(`/theme-settings/${storeId}/product-page`, data)
export const updateCollectionPage = (storeId, data) => api.put(`/theme-settings/${storeId}/collection-page`, data)
export const updateCart = (storeId, data) => api.put(`/theme-settings/${storeId}/cart`, data)
export const updateCheckout = (storeId, data) => api.put(`/theme-settings/${storeId}/checkout`, data)
export const updateMobile = (storeId, data) => api.put(`/theme-settings/${storeId}/mobile`, data)
export const updateSpacing = (storeId, data) => api.put(`/theme-settings/${storeId}/spacing`, data)
export const updateCustomCss = (storeId, css) => api.put(`/theme-settings/${storeId}/css`, { css })
export const updateCustomHtml = (storeId, data) => api.put(`/theme-settings/${storeId}/html`, data)
export const updateBulk = (storeId, data) => api.put(`/theme-settings/${storeId}/bulk`, data)
export const resetThemeSettings = (storeId) => api.post(`/theme-settings/${storeId}/reset`)
